fixed linters and added images
obibaadoma/PotfolioMic pull request #1
Opened 2023-05-31 16:55 UTC by obibaadoma

# Included Images
fixed linters

2023-05-31 18:13 UTC, shahadat3669 requested changes
Hi @obibaadoma , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not follow proper General requirements.

Your pull request is invalid due to the following reasons. Firstly, the pull request lacks a descriptive title that clearly indicates the changes made. Secondly, the summary of changes provided is not sufficiently detailed. It is important to include a concise summary in the pull request description, elaborating on the introduced changes. Additionally, the readme file needs to be updated with necessary project details, avoiding placeholder text from the readme template. Please address these issues by providing a descriptive title, a comprehensive summary of changes, and an updated readme file containing specific project information.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-05-31 22:48 UTC, Ofarouq310 reviewed
Hi @obibaadoma, ✋ 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## 🔴 Invalid Code Review Request

![giphy](https://github.com/obibaadoma/PotfolioMic/assets/102612396/334c06b6-7541-49d0-af78-12d761d674b8)

- Your `README` file is not customized to your project needs, you have just used the template as it is, Kindly edit the `README` template to match your project specs.

- Concerning commit messages, kindly make sure it should be written in the imperative tense and capitalized, take a closer look in the next picture for some great descriptive examples.
![image](https://github.com/obibaadoma/PotfolioMic/assets/102612396/2add25d8-4d4a-48fd-93e0-1dc1cc0c7011)

- Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

[OPTIONAL] 
Your branch should have a name of a feature or action you are implementing, in your case it could be "mobile-setup" or "header-and-deadline" or whatever suits you. Kindly fix it and rename your branch. Kindly refer to the next image for the steps of renaming a branch.
![image](https://github.com/Fentahunn/portfolio_one/assets/102612396/3212d6a3-479d-46d6-9bb2-e049ca9aa122)



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-05-31 23:55 UTC, bienvenuushindi requested changes
### Hi @obibaadoma     ,

Good job implementing most of the project requirements!
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://camo.githubusercontent.com/56bcd754643682fcc078b66eaa7278dead6c9c5013595c875b4ddcbe0f0ef0aa/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f78554f786668365a4d373565664d3342716f2f67697068792d646f776e73697a65642d6d656469756d2e676966)

## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- GitHub flow is used correctly. ✔
- All linters checks are ok. ✔


## (Changes Required) Aspects to improve: ♻️

- [ ] Please check the inline comments below.

## [Optional] suggestions:

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-05-31 23:55 UTC, bienvenuushindi commented on README.md
> +- write: git clone https://github.com/obibaadoma/HelloMic
:red_circle: Please make sure you include the right link here which is https://github.com/obibaadoma/PotfolioMic.git

2023-05-31 23:55 UTC, bienvenuushindi commented on README.md
> +## 🚀 Live Demoemo <a name="not available"></a>
:red_circle: Please make sure you correct this typo error. It should be **Live Demo**

2023-05-31 23:55 UTC, bienvenuushindi commented on README.md
> +- Git, Github and Visual Studio Code
:red_circle: This file should just have one **Built with** section. Currently, you have two sections Please make sure you remove this one

2023-05-31 23:55 UTC, bienvenuushindi commented on README.md
> +
:red_circle: This file should just have one **Getting Started** section. Currently, you have two sections Please make sure you remove the additional one.

2023-05-31 23:55 UTC, bienvenuushindi commented on README.md
> +
:red_circle: To have a professional Readme, please make sure to include the content for these two sections:

2023-05-31 23:55 UTC, bienvenuushindi commented on README.md
> +> Mention all of the collaborators of this project.
:red_circle: Please remove this paragraph as it is a placeholder. It is only here to give you an idea of what should be in this section.

2023-05-31 23:55 UTC, bienvenuushindi commented on index.html
> +  <section class="headline">
:red_circle: Please make sure you add the proper background image as it is on the [Figma Design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?type=design&node-id=39-122)

Note: As  the image is not part of the content kindly  use CSS background-image. [Check this link](https://stackoverflow.com/questions/492809/when-to-use-img-vs-css-background-image) for more info.

Your Design
![no-bg](https://github.com/obibaadoma/PotfolioMic/assets/26736582/efa8bc1b-7d80-4d86-b273-83301079cbee)

Figma

![bg](https://github.com/obibaadoma/PotfolioMic/assets/26736582/aaba7934-1409-41d4-b180-60e2d3bf6355)

2023-06-01 01:57 UTC, obibaadoma commented on README.md
> +- Git, Github and Visual Studio Code
Do you mean i should resolve it by taking out line 63 totally

2023-06-01 02:06 UTC, obibaadoma commented on README.md
> +
fixed

2023-06-01 02:07 UTC, obibaadoma commented on README.md
> +> Mention all of the collaborators of this project.
Kindly further clarify what i am supposed to do here, do i have to remove line 87 or write my name as the author in line 85

2023-06-01 02:10 UTC, obibaadoma commented on index.html
> +  <section class="headline">
my design is same as what is in figma

2023-06-01 02:44 UTC, emmiiorji requested changes
Hi @obibaadoma, 

# Status: Approved ✅

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<div align='center'>
<img src='https://user-images.githubusercontent.com/20554583/220871050-9893fe6a-46a0-42a3-8a44-46ac0f7f1154.gif'/>
</div>

## Good Highlights✔️

- Good design
- File structure is organized

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-01 02:44 UTC, emmiiorji commented on style.css
> +  background: #fff url(../images/header.png);
[Optional] Well done for properly using a background image here instead of an img element. It renders well on a local server but might have some issue rendering on an online server. In relation to the location of the style.css file, the path to the image would be `/images/header.png` instead of `../images/header.png`. I suggest that you modify it to the correct relative path.

2023-06-01 02:46 UTC, emmiiorji approved these changes
Hi @obibaadoma, 

# Status: Approved ✅

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<div align='center'>
<img src='https://user-images.githubusercontent.com/20554583/220871050-9893fe6a-46a0-42a3-8a44-46ac0f7f1154.gif'/>
</div>

## Good Highlights✔️

- Good design
- File structure is organized

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-01 02:46 UTC, emmiiorji commented on style.css
> +  background: #fff url(../images/header.png);
[Optional] Well done for properly using a background image here instead of an img element. It renders well on a local server but might have some issue rendering on an online server. In relation to the location of the style.css file, the path to the image would be `/images/header.png` instead of `../images/header.png`. I suggest that you modify it to the correct relative path.

2023-06-01 03:52 UTC, merged